### ISSUE TITLE
Soporte para xOMS

### ISSUE THREAD

**Issue by nacho-herrera** [ggallohernandez/pymatriz#3]
Hola, como va? Encontré este desarrollo en twitter y me puse a curiosearlo. Esta buenísimo, me gustaría probarlo pero tengo una limitación. Si aceptas una sugerencia estaría bueno que soporte también la versión de Matriz que corre bajo el OMS de Primary llamado xOMS. En lineas generales son los mismos métodos, solo difiere el endpoint (cada alyc que use esa plataforma tiene uno diferente) y el método de autenticación ya que aun no tienen implementado Auth0. Estaría bueno ya que son mas los agentes que usan xOMS hoy en día que Matriz directo. en web.talaris.com.ar > Iniciar sesión podes ver la lista de agentes habilitados. 
Desde ya mil gracias y a disposición por cualquier consulta que mi pedido, si es que te interesa indagar, te genere. 
Saludos
@nachoherrera en twitter

**Comment by ggallohernandez** [comment]
Muy buen dato, conocia la app Talaris, pero no conocia la version web, que me facilita mucho ver la interacción HTTP para poder hacer un API, ya estoy jugando con esa plataforma. Voy a pensar si conviene agregar soporte en el mismo repo o crear uno nuevo.

Gracias por el aviso!

**Comment by ggallohernandez** [comment]
Se marca como won't fix ya que es otra API distinta a Matriz, se va a encarar en nuevo repo.
